In [2]:
print("hello pytorch!")

hello pytorch!


In [3]:
import torch

In [4]:
x = torch.rand(5,3)

In [5]:
x

tensor([[0.9145, 0.1306, 0.7856],
        [0.7034, 0.2832, 0.8019],
        [0.7337, 0.8811, 0.4020],
        [0.2774, 0.0489, 0.4684],
        [0.5335, 0.2139, 0.8742]])

In [6]:
y = torch.ones(5,3)

In [7]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
z = torch.zeros(5,3)

In [9]:
z

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
z = torch.zeros(2, 5, 3)
z

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [11]:
z[0]

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
z[0][:,2]

tensor([0., 0., 0., 0., 0.])

In [13]:
x[1,2]

tensor(0.8019)

In [14]:
x[:,2]

tensor([0.7856, 0.8019, 0.4020, 0.4684, 0.8742])

In [15]:
z = x + y

In [16]:
z

tensor([[1.9145, 1.1306, 1.7856],
        [1.7034, 1.2832, 1.8019],
        [1.7337, 1.8811, 1.4020],
        [1.2774, 1.0489, 1.4684],
        [1.5335, 1.2139, 1.8742]])

In [17]:
q = x.mm(y.t())
q

tensor([[1.8307, 1.8307, 1.8307, 1.8307, 1.8307],
        [1.7886, 1.7886, 1.7886, 1.7886, 1.7886],
        [2.0168, 2.0168, 2.0168, 2.0168, 2.0168],
        [0.7947, 0.7947, 0.7947, 0.7947, 0.7947],
        [1.6217, 1.6217, 1.6217, 1.6217, 1.6217]])

In [18]:
import numpy as np

x_tensor = torch.randn(2,3)
x_tensor

tensor([[-1.2390, -1.5650,  0.0796],
        [ 0.3884,  0.5835,  0.9040]])

In [19]:
y_numpy = np.random.randn(2,3)
y_numpy

array([[-1.61813609, -0.07855434,  0.59392436],
       [ 1.30647944, -0.05459259, -0.3791096 ]])

In [20]:
x_numpy = x_tensor.numpy()
x_numpy

array([[-1.2389777 , -1.56502   ,  0.07958511],
       [ 0.3884182 ,  0.583458  ,  0.90397483]], dtype=float32)

In [21]:
y_tensor = torch.from_numpy(y_numpy)
y_tensor

tensor([[-1.6181, -0.0786,  0.5939],
        [ 1.3065, -0.0546, -0.3791]], dtype=torch.float64)

In [22]:
torch.cuda.is_available()

False

In [56]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [60]:
y = x + 2
y.grad_fn

In [25]:
y.grad

/tmp/ipykernel_673540/486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647175880/work/build/aten/src/ATen/core/TensorBody.h:489.)
  y.grad


In [26]:
y.grad_fn

In [27]:
z = y * y
z

tensor([[9., 9.],
        [9., 9.]], grad_fn=<MulBackward0>)

In [28]:
z.grad_fn

In [29]:
t = torch.mean(z)
t

tensor(9., grad_fn=<MeanBackward0>)

In [30]:
t.grad_fn

In [31]:
t.backward()

In [33]:
print(t.grad)

None


/tmp/ipykernel_673540/3566409831.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647175880/work/build/aten/src/ATen/core/TensorBody.h:489.)
  print(t.grad)


In [34]:
print(z.grad)

None


/tmp/ipykernel_673540/2878411509.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647175880/work/build/aten/src/ATen/core/TensorBody.h:489.)
  print(z.grad)


In [35]:
print(y.grad)

None


/tmp/ipykernel_673540/1324337507.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647175880/work/build/aten/src/ATen/core/TensorBody.h:489.)
  print(y.grad)


In [36]:
print(x.grad)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


In [37]:
s = torch.tensor([[0.01, 0.02]], requires_grad=True)
s

tensor([[0.0100, 0.0200]], requires_grad=True)

In [38]:
x = torch.ones(2,2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [39]:
for i in range(10):
    s = s.mm(x)

z = torch.mean(s)

In [40]:
z

tensor(15.3600, grad_fn=<MeanBackward0>)

In [41]:
z.backward()
print(x.grad)
print(s.grad)

tensor([[37.1200, 37.1200],
        [39.6800, 39.6800]])
None


/tmp/ipykernel_673540/3606434708.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647175880/work/build/aten/src/ATen/core/TensorBody.h:489.)
  print(s.grad)


In [42]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 1

In [43]:
y

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [46]:
z = y * y
z

tensor([[4., 4.],
        [4., 4.]], grad_fn=<MulBackward0>)

In [49]:
z.sum().backward()

In [50]:
z.grad

/tmp/ipykernel_673540/4110045842.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647175880/work/build/aten/src/ATen/core/TensorBody.h:489.)
  z.grad


In [51]:
x.grad

tensor([[4., 4.],
        [4., 4.]])

In [52]:
y.grad_fn

In [53]:
x.grad_fn

In [54]:
z.grad_fn

In [55]:
z.sum().grad_fn

In [61]:
x = torch.tensor(10., requires_grad=True)
y = x + 1


In [62]:
y.backward()

In [63]:
x.grad

tensor(1.)

In [64]:
y.grad

/tmp/ipykernel_673540/486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647175880/work/build/aten/src/ATen/core/TensorBody.h:489.)
  y.grad


In [66]:
x = torch.tensor([[10., 10.]], requires_grad=True)
y = x + 1
z = torch.mean(y)
z

tensor(11., grad_fn=<MeanBackward0>)

In [67]:
z.backward()

In [68]:
x.grad

tensor([[0.5000, 0.5000]])