In [1]:
print("hello pytorch!")

hello pytorch!


In [2]:
import torch

In [3]:
x = torch.rand(5,3)

In [4]:
x

tensor([[0.8718, 0.4817, 0.0399],
        [0.4085, 0.1511, 0.2417],
        [0.7388, 0.7982, 0.9518],
        [0.3453, 0.9646, 0.5266],
        [0.7929, 0.1881, 0.2295]])

In [5]:
y = torch.ones(5,3)

In [6]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
z = torch.zeros(5,3)

In [8]:
z

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
z = torch.zeros(2, 5, 3)
z

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [10]:
z[0]

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
z[0][:,2]

tensor([0., 0., 0., 0., 0.])

In [12]:
x[1,2]

tensor(0.2417)

In [13]:
x[:,2]

tensor([0.0399, 0.2417, 0.9518, 0.5266, 0.2295])

In [14]:
z = x + y

In [15]:
z

tensor([[1.8718, 1.4817, 1.0399],
        [1.4085, 1.1511, 1.2417],
        [1.7388, 1.7982, 1.9518],
        [1.3453, 1.9646, 1.5266],
        [1.7929, 1.1881, 1.2295]])

In [16]:
q = x.mm(y.t())
q

tensor([[1.3934, 1.3934, 1.3934, 1.3934, 1.3934],
        [0.8012, 0.8012, 0.8012, 0.8012, 0.8012],
        [2.4888, 2.4888, 2.4888, 2.4888, 2.4888],
        [1.8365, 1.8365, 1.8365, 1.8365, 1.8365],
        [1.2106, 1.2106, 1.2106, 1.2106, 1.2106]])

In [17]:
import numpy as np

x_tensor = torch.randn(2,3)
x_tensor

tensor([[-0.3726,  0.3835, -0.1237],
        [-0.7973,  0.4626, -0.0668]])

In [18]:
y_numpy = np.random.randn(2,3)
y_numpy

array([[-0.32581136,  0.92988396, -0.074781  ],
       [ 1.91309714, -0.84458311,  0.25418791]])

In [19]:
x_numpy = x_tensor.numpy()
x_numpy

array([[-0.3725793 ,  0.38354534, -0.12371133],
       [-0.79726905,  0.46256185, -0.06680126]], dtype=float32)

In [20]:
y_tensor = torch.from_numpy(y_numpy)
y_tensor

tensor([[-0.3258,  0.9299, -0.0748],
        [ 1.9131, -0.8446,  0.2542]], dtype=torch.float64)

In [21]:
torch.cuda.is_available()

False

In [22]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [23]:
y = x + 2
y.grad_fn

In [24]:
y.grad

/tmp/ipykernel_141386/486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647175880/work/build/aten/src/ATen/core/TensorBody.h:489.)
  y.grad


In [25]:
y.grad_fn

In [26]:
z = y * y
z

tensor([[9., 9.],
        [9., 9.]], grad_fn=<MulBackward0>)

In [27]:
z.grad_fn

In [28]:
t = torch.mean(z)
t

tensor(9., grad_fn=<MeanBackward0>)

In [29]:
t.grad_fn

In [30]:
t.backward()

In [31]:
print(t.grad)

None


/tmp/ipykernel_141386/3566409831.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647175880/work/build/aten/src/ATen/core/TensorBody.h:489.)
  print(t.grad)


In [32]:
print(z.grad)

None


/tmp/ipykernel_141386/2878411509.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647175880/work/build/aten/src/ATen/core/TensorBody.h:489.)
  print(z.grad)


In [33]:
print(y.grad)

None


/tmp/ipykernel_141386/1324337507.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647175880/work/build/aten/src/ATen/core/TensorBody.h:489.)
  print(y.grad)


In [34]:
print(x.grad)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


In [35]:
s = torch.tensor([[0.01, 0.02]], requires_grad=True)
s

tensor([[0.0100, 0.0200]], requires_grad=True)

In [36]:
x = torch.ones(2,2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [37]:
for i in range(10):
    s = s.mm(x)

z = torch.mean(s)

In [38]:
z

tensor(15.3600, grad_fn=<MeanBackward0>)

In [39]:
z.backward()
print(x.grad)
print(s.grad)

tensor([[37.1200, 37.1200],
        [39.6800, 39.6800]])
None


/tmp/ipykernel_141386/3606434708.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647175880/work/build/aten/src/ATen/core/TensorBody.h:489.)
  print(s.grad)


In [40]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 1

In [41]:
y

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [42]:
z = y * y
z

tensor([[4., 4.],
        [4., 4.]], grad_fn=<MulBackward0>)

In [43]:
z.sum().backward()

In [44]:
z.grad

/tmp/ipykernel_141386/4110045842.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647175880/work/build/aten/src/ATen/core/TensorBody.h:489.)
  z.grad


In [45]:
x.grad

tensor([[4., 4.],
        [4., 4.]])

In [46]:
y.grad_fn

In [47]:
x.grad_fn

In [48]:
z.grad_fn

In [49]:
z.sum().grad_fn

In [50]:
x = torch.tensor(10., requires_grad=True)
y = x + 1


In [51]:
y.backward()

In [52]:
x.grad

tensor(1.)

In [53]:
y.grad

/tmp/ipykernel_141386/486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647175880/work/build/aten/src/ATen/core/TensorBody.h:489.)
  y.grad


In [54]:
x = torch.tensor([[10., 10.]], requires_grad=True)
y = x + 1
z = torch.mean(y)
z

tensor(11., grad_fn=<MeanBackward0>)

In [55]:
z.backward()

In [56]:
x.grad

tensor([[0.5000, 0.5000]])

In [57]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
x = x.view(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [59]:
x = x.view(4, 3)
x

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [60]:
x = x.view(1, -1)
x

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [61]:
x = x.view(-1, 1)
x

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])

In [65]:
x = torch.tensor([1000.0, 2000.0, 30000.0])
softmax = torch.functional.F.softmax(x, dim=0)
softmax

tensor([0., 0., 1.])

In [66]:
softmax = torch.exp(x) / torch.exp(x).sum()
log_softmax = torch.log(softmax)
log_softmax

tensor([nan, nan, nan])

In [64]:
log_softmax = torch.functional.F.log_softmax(x, dim=0)
log_softmax

tensor([-29000., -28000.,      0.])